# Generated by Django 5.2.6 on 2026-01-17 11:37

import common.push_id
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(default=common.push_id.push_id, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('position', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaySchedule',
            fields=[
                ('id', models.CharField(default=common.push_id.push_id, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('venue', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerAttendance',
            fields=[
                ('id', models.CharField(default=common.push_id.push_id, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.player')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.playschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPlayer',
            fields=[
                ('id', models.CharField(default=common.push_id.push_id, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
