# Generated by Django 5.2.6 on 2026-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_playschedule_date_alter_playschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerattendance',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
